server:
  port: 8080

spring:
  application:
    name: storage-node
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

node:
  name: ${NODE_NAME:server-local}
  region: ${NODE_REGION:LOCAL}

fault-detector:
  url: http://fault-detector:8083/api/health/heartbeat
